version: '3'
services:
    angular:
        image: node:10-alpine
        working_dir: /usr/app
        volumes:
            - ./src/frontend:/usr/app
            - /usr/app/node_modules
        expose:
            - "4200"
        ports:
            - "4200:4200"
        command: /bin/sh -c "npm install -g @angular/cli && npm install -f && ng serve --host 0.0.0.0 --disable-host-check --deploy-url /app"
        restart: always

    spring:
        image: maven:3-jdk-11-slim
        working_dir: /app
        volumes:
            - ./src/backend:/app
        expose:
            - "8080"
        ports:
            - "8080:8080"
        command: mvn clean spring-boot:run
        restart: always

    nginx:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"
        restart: always
        depends_on:
            - angular
            - spring
